### ISSUE TITLE
Exposed mongodb credentials

### ISSUE THREAD

**Issue by eth0izzle** [ma-9/Shopping-Cart-Using-Node#4]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@ds127938.mlab.com` in file [/app.js](https://github.com/ma-9/E_com_NodeJS/blob/master/app.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by ma-9** [comment]
Thanks for Helping me
